---
abstract: unknown
author:
  - 'Damian Gryski <damian@gryski.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ShardedKV-Continuum-Jump
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::ConsistentHash::JumpHash: 0.03
version: 0.02
